### ISSUE TITLE
Improve SDK

### ISSUE THREAD

**Issue by corbadoman** [corbado/corbado-nodejs#17]
# Why

For our launch we need to polish our SDK as much as possible. 

The plan is to adapt as much as possible from our Corbado PHP SDK (https://www.github.com/corbado/corbado-php, branch 16-improve-sdk) but only if "no one" is doing it different in the JavaScript/TypeScript world (discuss before implementation if in doubt).

If you need to research "how others are doing something" we always look at Stripe SDKs and Auth0 SDKs.

# TODOS

- [x] Port everything to TypeScript
- [x] Adapt PHP directory structure (have services directory etc.) 3-Days
   - [x] Should we use interfaces for our services?
   - [x] Implement all services PHP provides
   - [x] Implement good error handling, probably use exceptions? In case of HTTP status codes other than 200 data should be easy accessible (see PHP ServerException)
- [x] Add script to generate OpenAPI code (see PHP /scripts)
   - [x] Add command to npm 
- [x] Add tools to improve sourcecode
   - [x] eslint / eslint-ts?
   - [x] prettier? 
   - [x] Add commands to npm
- [x] Introduce X-Corbado-SDK header to every call (with JSON payload), see PHP
   - [x] Key "name" with "Node.js SDK"
   - [x] Key "sdkVersion" with current SDK version
   - [x] Key "languageVersion" with current JavaScript version (Node.js?)
- [x] Add integration tests (/tests/integration directory) - 1.5-Days
   - [x] See PHP as well
   - [x] What framework do we use and why? 
   - [x] Add command to npm
- [x] Adapt README.md from PHP
   - [ ] Use nice badges (which are common in the JavaScript/TypeScript world)
   - [x] Differentiate between ES5 and ES6 (see current README.md)
- [x] Add GitHub action 1-Day
   - [x] Adapt from PHP (structure, naming)
- [x] Test under JavaScript and TypeScript scenarios? 1-Day
   - [x]  What versions (see matrix) do we check?
- [ ] Update references/usages of this SDK in Corbado world 2-Days
   - [x] Update documentation (https://docs.corbado.com)
   - [x] Update wizards
   - [ ] Update landing pages (e.g. https://www.corbado.com/passkeys/node-js)

# New TODOS

- [x] Add "private client" info to README.md
- [x] Check if SDK runs in browser, if yes alert/throw exception (since the SDK needs an API secret it must NEVER EVERY run in an browser/public environment)

The Node.js SDK (Express) is commonly referred to as a private client, specifically designed for usage within closed backend applications. This particular SDK should exclusively be utilized in such environments, as it is crucial to ensure that the API secret remains strictly confidential and is never shared.

# Acceptance criteria

- [ ] Full service coverage as in PHP
- [ ] Everything works for JavaScript and TypeScript developers
