### ISSUE TITLE
Upgrade SDK to OpenAPI v2

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/corbado-nodejs#27]
# Background
Due to the upgrade to OpenAPI v2, we need to adapt our Node.js Backend SDK as well. We will cut down on the services to only three:
- sessions
- users
- identifiers

This implies some more changes as well (see below).

# TODO
- [ ] Implement the three new services / cut the SDKs down to these three (see above).
- [ ] Change the Corbado Backend API to "https://backendapi.cloud.corbado.io"
- [ ] Update the respective README accordingly
- [ ] Please check the code examples (if applicable) and see if we need to update things there as well:
   - [ ] Blog post for Node.js (https://www.corbado.com/blog/nodejs-passkeys)
   - [ ] Update the corresponding example app (https://github.com/corbado/example-passkeys-nodejs)
   - [ ] Blog post for Next.js (https://www.corbado.com/blog/nextjs-passkeys)
   - [ ] Update the corresponding example app (https://github.com/corbado/example-passkeys-nextjs)
   - [ ] Wizard (https://app.corbado.com/`<project-ID>`/project-setup/nodejs)

**Comment by corbadoman** [comment]
all done
